name: state_flow
description: "StateFlow provides a simple and efficient way to manage state in your Flutter applications."
version: 0.0.5
homepage: https://github.com/tusharhow/StateFlow

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
